### PR TITLE
Bump version to 1.4.0

### PR DESCRIPTION
**Pull request by icedevml**

### CODE REVIEW

**Comment by msm-code** [comment]
Didn't we have a release literally 1h ago? https://github.com/CERT-Polska/ursadb/releases

Bumping a version with no changes looks weird

**Comment by icedevml** [comment]
@msm-code We have to set up the convention here. As we've released 1.3.0, everything that is newer than 1a027ca834af814e026d92ec6f4d695141d62180 belongs to the new version (at least IMO).

**Comment by chivay** [comment]
I think that bumping version should be the last thing before the release (Linux kernel does it, so it must be right ;) ). 

However, building debs between releases is an issue that must be addressed.

Thus, I propose to keep current convention and bump the major/minor/patch versions just before release and to version the master branch builds  as:
 `MAJOR.MINOR.PATCH-dev-timestamp`, for example `1.3.0-dev-20200413213700`

**Comment by msm-code** [comment]
First of all, I (really) believe that we should follow https://semver.org/ for versioning. So let's just take everything from semver spec as a dogma. 

This clears up a few questions, but also raises some problems

> Thus, I propose to keep current convention and bump the major/minor/patch versions just before release and to version the master branch builds as:
> `MAJOR.MINOR.PATCH-dev-timestamp`, for example `1.3.0-dev-20200413213700`

 Nitpick: `1.3.0-dev+20200413213700` (plus sign) to be compatible with https://semver.org/.

But the problem is, `-dev` is treated as a pre-release version, which is used when comparing version order (`1.3.0-alpha` < `1.3.0-dev` < `1.3.0` < `1.4.0-dev`).

There are also issues with bumping the version right now. For example, how do we know that the next version is going to be `1.4.0`? Why not `1.3.1` or `2.0.0`? We could work around it by always incrementing the last number (patch) and deciding on the version later, but it's ugly.

I've though for a while about this, and I think we:
 - should bump the version just before the release (as @chivay has said)
 - should add a build ID to unreleased versions. So the commit after `1.3.0` will be build as `1.3.0+202012131` for example.
 - shouldn't worry too much unreleased versions. Doing this with a proper versioning is basically impossible anyway. If someone installs a deb for `1.4.0 yet unreleased version` on their production, they're on their own. 

Thoughts?

**Comment by chivay** [comment]
LGTM

**Comment by icedevml** [comment]
LGTM

**Pull request closed without merging**
